name: inventario_umsa_industrial2019
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  cloud_firestore: ^0.12.9+6
  qr_flutter: ^3.0.1
  firebase_storage: ^3.0.6
  path_provider: ^1.4.0
  qr_code_scanner: ^0.0.12
  permission_handler: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/fondo.jpg
    - assets/images/fondo1.png
    - assets/images/logo.png

  fonts:
    - family: Icons
      fonts:
        - asset: assets/fonts/panaderia.ttf
    - family: IconsMovimiento
      fonts:
        - asset: assets/fonts/movimientos.ttf
